# Generated by Django 4.2 on 2025-08-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_remove_group_members_alter_group_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="description",
            field=models.TextField(default=1, max_length=511),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="groupinvitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("revoked", "Revoked"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
