# Generated by Django 4.2 on 2025-08-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="description",
            field=models.CharField(max_length=511, null=True),
        ),
    ]
